"""initial schema — all Phase 1 + Phase 3 models

Revision ID: 5c5d124c4ef3
Revises: 
Create Date: 2026-03-04 22:02:50.701412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5d124c4ef3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('fd_uk_code', sa.String(length=20), nullable=True),
    sa.Column('fbref_id', sa.String(length=50), nullable=True),
    sa.Column('understat_name', sa.String(length=100), nullable=True),
    sa.Column('season_format', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('fixtures_count', sa.Integer(), nullable=True),
    sa.Column('predictions_count', sa.Integer(), nullable=True),
    sa.Column('picks_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_run_date', 'pipeline_runs', ['run_date'], unique=False)
    op.create_table('raw_staging_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_staging_records_status', 'raw_staging_records', ['status'], unique=False)
    op.create_table('source_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_failure', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('rows_collected', sa.Integer(), nullable=False),
    sa.Column('avg_collection_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_health_source_name', 'source_health', ['source_name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('elo_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.Date(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'rating_date', 'source')
    )
    op.create_index('ix_elo_ratings_rating_date', 'elo_ratings', ['rating_date'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=200), nullable=False),
    sa.Column('away_team', sa.String(length=200), nullable=False),
    sa.Column('league', sa.String(length=200), nullable=False),
    sa.Column('prob_home', sa.Float(), nullable=True),
    sa.Column('prob_draw', sa.Float(), nullable=True),
    sa.Column('prob_away', sa.Float(), nullable=True),
    sa.Column('prob_over', sa.Float(), nullable=True),
    sa.Column('prob_under', sa.Float(), nullable=True),
    sa.Column('prob_btts_yes', sa.Float(), nullable=True),
    sa.Column('prob_btts_no', sa.Float(), nullable=True),
    sa.Column('xgboost_probs', sa.JSON(), nullable=True),
    sa.Column('poisson_probs', sa.JSON(), nullable=True),
    sa.Column('ensemble_weights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_match_date', 'predictions', ['match_date'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=200), nullable=False),
    sa.Column('away_team', sa.String(length=200), nullable=False),
    sa.Column('league', sa.String(length=200), nullable=False),
    sa.Column('pick_market', sa.String(length=20), nullable=False),
    sa.Column('pick_selection', sa.String(length=50), nullable=False),
    sa.Column('model_prob', sa.Float(), nullable=False),
    sa.Column('model_spread', sa.Float(), nullable=False),
    sa.Column('best_odds', sa.Float(), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('meta_agreement', sa.Integer(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('stake_flat', sa.Float(), nullable=True),
    sa.Column('stake_kelly', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('broadcasted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_picks_match_date', 'daily_picks', ['match_date'], unique=False)
    op.create_index('ix_daily_picks_result', 'daily_picks', ['result'], unique=False)
    op.create_index('ix_daily_picks_tier', 'daily_picks', ['tier'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('kick_off_time', sa.String(length=10), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('home_goals_ht', sa.Integer(), nullable=True),
    sa.Column('away_goals_ht', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=1), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('referee', sa.String(length=200), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'match_date', 'home_team_id', 'away_team_id')
    )
    op.create_index('ix_matches_match_date', 'matches', ['match_date'], unique=False)
    op.create_index('ix_matches_status', 'matches', ['status'], unique=False)
    op.create_table('competitor_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('predicted_result', sa.String(length=1), nullable=True),
    sa.Column('prob_home', sa.Float(), nullable=True),
    sa.Column('prob_draw', sa.Float(), nullable=True),
    sa.Column('prob_away', sa.Float(), nullable=True),
    sa.Column('predicted_score_home', sa.Integer(), nullable=True),
    sa.Column('predicted_score_away', sa.Integer(), nullable=True),
    sa.Column('btts_prediction', sa.Boolean(), nullable=True),
    sa.Column('over_under_prediction', sa.String(length=10), nullable=True),
    sa.Column('over_under_line', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'source')
    )
    op.create_table('match_odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('odds_type', sa.String(length=20), nullable=False),
    sa.Column('odds_home', sa.Float(), nullable=True),
    sa.Column('odds_draw', sa.Float(), nullable=True),
    sa.Column('odds_away', sa.Float(), nullable=True),
    sa.Column('odds_over', sa.Float(), nullable=True),
    sa.Column('odds_under', sa.Float(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'bookmaker', 'market', 'odds_type')
    )
    op.create_index('ix_match_odds_match_id', 'match_odds', ['match_id'], unique=False)
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('home_possession', sa.Float(), nullable=True),
    sa.Column('home_passes', sa.Integer(), nullable=True),
    sa.Column('home_pass_accuracy', sa.Float(), nullable=True),
    sa.Column('home_fouls', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('home_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('home_red_cards', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_possession', sa.Float(), nullable=True),
    sa.Column('away_passes', sa.Integer(), nullable=True),
    sa.Column('away_pass_accuracy', sa.Float(), nullable=True),
    sa.Column('away_fouls', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('away_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('away_red_cards', sa.Integer(), nullable=True),
    sa.Column('extra_stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('match_weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('match_xg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('home_npxg', sa.Float(), nullable=True),
    sa.Column('away_npxg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_xg')
    op.drop_table('match_weather')
    op.drop_table('match_stats')
    op.drop_index('ix_match_odds_match_id', table_name='match_odds')
    op.drop_table('match_odds')
    op.drop_table('competitor_predictions')
    op.drop_index('ix_matches_status', table_name='matches')
    op.drop_index('ix_matches_match_date', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_daily_picks_tier', table_name='daily_picks')
    op.drop_index('ix_daily_picks_result', table_name='daily_picks')
    op.drop_index('ix_daily_picks_match_date', table_name='daily_picks')
    op.drop_table('daily_picks')
    op.drop_table('seasons')
    op.drop_index('ix_predictions_match_date', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_elo_ratings_rating_date', table_name='elo_ratings')
    op.drop_table('elo_ratings')
    op.drop_table('teams')
    op.drop_index('ix_source_health_source_name', table_name='source_health')
    op.drop_table('source_health')
    op.drop_index('ix_raw_staging_records_status', table_name='raw_staging_records')
    op.drop_table('raw_staging_records')
    op.drop_index('ix_pipeline_runs_run_date', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('leagues')
    # ### end Alembic commands ###
